### ISSUE TITLE
Same metric being created with newlines

### ISSUE THREAD

**Issue by heitorlessa** [lumigo/SAR-async-lambda-metrics#7]
Metrics with dimension values are being duplicated with `\n`. Unsure whether this is being caused by some data mangling from within Kinesis or some parsing yet - Perhaps [trim dimension value could](https://github.com/lumigo/SAR-async-lambda-metrics/blob/master/functions/lib.js#L27) prevent that from happening.

**Expected**

* Create a metric named **InvalidPaymentRequest** with `service` and `operation` as dimensions

```json
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "InvalidPaymentRequest",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "operation",
                    "Value": "collect_payment"
                }
            ]
        },
```

* Create a metric named **ColdStart** with `service` and `function_name` as dimensions

```json
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "ColdStart",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "function_name",
                    "Value": "awsserverlessairline-london-2019090-CollectPayment-YT42VJ6EBNKD"
                }
            ]
        },
```

**Actual**

Here's all metrics variation it ended up creating:

```json
{
    "Metrics": [
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "ColdStart",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "function_name",
                    "Value": "awsserverlessairline-london-2019090-CollectPayment-YT42VJ6EBNKD\\\\n\\'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "InvalidPaymentRequest",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "operation",
                    "Value": "collect_payment\\\\n\\'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "ColdStart",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "function_name",
                    "Value": "awsserverlessairline-london-2019090-CollectPayment-YT42VJ6EBNKD\\n'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "InvalidPaymentRequest",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "operation",
                    "Value": "collect_payment\\n'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "ColdStart",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "function_name",
                    "Value": "awsserverlessairline-london-2019090-CollectPayment-YT42VJ6EBNKD"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "InvalidPaymentRequest",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "operation",
                    "Value": "collect_payment"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "ColdStart",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "function_name",
                    "Value": "awsserverlessairline-london-2019090-CollectPayment-YT42VJ6EBNKD\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "InvalidPaymentRequest",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "operation",
                    "Value": "collect_payment\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "ColdStart",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "function_name",
                    "Value": "awsserverlessairline-london-2019090-CollectPayment-YT42VJ6EBNKD\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "InvalidPaymentRequest",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "operation",
                    "Value": "collect_payment\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "ColdStart",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "booking"
                },
                {
                    "Name": "function_name",
                    "Value": "awsserverlessairline-london-2019090-CollectPayment-YT42VJ6EBNKD\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "InvalidPaymentRequest",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "booking"
                },
                {
                    "Name": "operation",
                    "Value": "collect_payment\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "ColdStart",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "booking"
                },
                {
                    "Name": "function_name",
                    "Value": "awsserverlessairline-london-2019090-CollectPayment-YT42VJ6EBNKD\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "InvalidPaymentRequest",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "booking"
                },
                {
                    "Name": "operation",
                    "Value": "collect_payment\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "ColdStart",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "booking"
                },
                {
                    "Name": "function_name",
                    "Value": "awsserverlessairline-london-2019090-CollectPayment-YT42VJ6EBNKD\\\\\\\\n\\\\\\'"
                }
            ]
        },
        {
            "Namespace": "ServerlessAirline",
            "MetricName": "InvalidPaymentRequest",
            "Dimensions": [
                {
                    "Name": "service",
                    "Value": "payment"
                },
                {
                    "Name": "operation",
                    "Value": "collect_payment\\\\\\\\n\\\\\\'"
                }
            ]
        }
    ]
}
```

**Comment by heitorlessa** [comment]
Log output from collect_payment function:

```python
START RequestId: e86387dd-fb55-466f-9d23-4a25a55cf2c4 Version: $LATEST
MONITORING|1|Count|InvalidPaymentRequest|ServerlessAirline|service=payment,operation=collect_payment
{
    "timestamp": "2019-09-07 07:59:14,507",
    "level": "ERROR",
    "location": "payment.lambda_handler:134",
    "service": "payment",
    "cold_start": "false",
    "function_name": "awsserverlessairline-london-2019090-CollectPayment-YT42VJ6EBNKD",
    "function_memory_size": "128",
    "function_arn": "arn:aws:lambda:eu-west-2:231436140809:function:awsserverlessairline-london-2019090-CollectPayment-YT42VJ6EBNKD",
    "function_request_id": "e86387dd-fb55-466f-9d23-4a25a55cf2c4",
    "message": {
        "operation": "invalid_event",
        "details": {
            "key1": "value1",
            "key2": "value2",
            "key3": "value3"
        }
    }
}
[ERROR] ValueError: Invalid Charge ID
Traceback (most recent call last):
  File "/var/task/lambda_python_powertools/tracing/tracer.py", line 172, in decorate
    raise err
  File "/var/task/lambda_python_powertools/tracing/tracer.py", line 164, in decorate
    response = lambda_handler(event, context)
  File "/var/task/lambda_python_powertools/logging/logger.py", line 185, in decorate
    return lambda_handler(event, context)
  File "/var/task/collect.py", line 135, in lambda_handler
    raise ValueError("Invalid Charge ID")
END RequestId: e86387dd-fb55-466f-9d23-4a25a55cf2c4
REPORT RequestId: e86387dd-fb55-466f-9d23-4a25a55cf2c4 Duration: 78.07 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 83 MB
XRAY TraceId: 1-5d736352-beb3f86ac6dfb8bd4cb20582 SegmentId: 142be7ce02d193fb 
```

**Comment by heitorlessa** [comment]
Trimming the value seems to be working, will test across multiple functions, and if that works consistently will send a PR:

```javascript
		// e.g. service=content-item,region=eu-west-1
		const dimensions = dimensionsCsv
			.split(',') // ['service=content-item', 'region=eu-west-1']
			.map(x => {
				const [ Name, Value ] = x.trim().split('=')
                                 // trimming excess newlines in dimension value 
				Value.trim()
				return { Name, Value }
			})
```

**Comment by heitorlessa** [comment]
No luck in reproducing this again in a new stack nor when writing tests to make a PR - Closing and considering this as non-reproducible.
